app/cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('cart/', CartDetailView.as_view(), name='cart_detail'),            # Детальное представление корзины
    path('cart/add/<int:product_id>', cart_add, name='cart_add'),           # Добавить товар в корзину
    path('cart/remove/<int:product_id>', cart_remove, name='cart_remove'),  # Убрать товар из корзины
]

app/online_shop/urls.py
from django.urls import path
from .views import *

app_name = 'online_shop'

urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    # path('order/create', order_create, name='order_create'),
    path('order/create', CreateOrderView.as_view(), name='order_create'),
    # path('order/<int:order_id>/pdf/', invoice_pdf, name='invoice_pdf'),
    path('product/<slug:slug>', ProductDetailView.as_view(), name='product_detail'),
    path('<slug:category_slug>', ProductListView.as_view(), name='product_list_by_category'),
    path('<slug:category_slug>/<slug:subcategory_slug>', ProductListView.as_view(), name='product_list_by_subcategory'),
    path('validate/', validate_postal_code, name='validate_postal_code'),
    

]

app/vape_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from vape_shop import settings
from main_app.views import index
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls), 
    path('main/', include('main_app.urls', namespace='admin_panel')),                                                                     
    path('accounts/', include('accounts.urls'), name='index_url'),                                                   
    path('seller/', include('seller_site.urls', namespace='local_shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('online_shop.urls', namespace='online_shop')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/main_app/models.py
from django.db import models
from django.db.models.query_utils import Q
from django.urls import reverse
from django.utils.timezone import pytz
from django.conf import settings
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver
from pytils.translit import slugify


class Category(models.Model):
    '''Модель категорий'''
    name = models.CharField(max_length=255, help_text='Имя категории')
    photo = models.ImageField(upload_to='category_img/', help_text='Фото категории')
    slug = models.SlugField(max_length=100, unique=True)
    pk_for_telegram = property(fget=lambda self: f'c||{self.pk}')    # Нужен для идентификации в телеграм боте
    max_count_product = models.IntegerField()

    def save(self, *args, **kwargs):
        if self.pk is not None:
            old_self = Category.objects.get(pk=self.pk)
            if old_self.photo and self.photo != old_self.photo:
                old_self.photo.delete(False)

        self.slug = slugify(self.name)
        return super(Category, self).save(*args, **kwargs)

    def get_absolute_url_for_shop(self):
        return reverse('online_shop:product_list_by_category', kwargs={'category_slug': self.slug})
        
    def __str__(self):
        return self.name

@receiver(pre_delete, sender=Category)
def photo_delete(sender, instance, **kwargs):
    if instance.photo.name:
        instance.photo.delete(False)


class SubCategory(models.Model):
    '''Модель подкатегорий'''
    category = models.ForeignKey(Category, on_delete=models.CASCADE, help_text='Категория подкатегории')
    name = models.CharField(max_length=150, db_index=True, help_text='Имя подкатегории')
    photo = models.ImageField(upload_to='subcategory_img/', help_text='Фотоподкатегории')
    slug = models.SlugField(max_length=100, unique=True)
    pk_for_telegram = property(fget=lambda self: f'sc||{self.pk}')

    def save(self, *args, **kwargs):
        if self.pk is not None:
            old_self = SubCategory.objects.get(pk=self.pk)
            if old_self.photo and self.photo != old_self.photo:
                old_self.photo.delete(False)

        self.slug = slugify(self.name)
        return super(SubCategory, self).save(*args, **kwargs)


    def get_absolute_url_for_shop(self):
        return reverse('online_shop:product_list_by_subcategory', kwargs={'category_slug': self.category.slug, 'subcategory_slug': self.slug})

    def __str__(self):
        return self.name


@receiver(pre_delete, sender=SubCategory)
def photo_delete(sender, instance, **kwargs):
    if instance.photo.name:
        instance.photo.delete(False)


class Product(models.Model):
    '''Модель товара'''
    title = models.CharField(max_length=255, verbose_name='Название товара')
    photo = models.ImageField(upload_to='product_img/', help_text='Фото товара')
    description = models.TextField(help_text='Описание товара')
    price = models.DecimalField(max_digits=10, decimal_places=2, help_text='Цена товара')
    count = models.IntegerField(default=0, help_text='Остаток на складе')
    slug = models.SlugField(max_length=100, unique=True)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE, help_text='Подкатегория товара')
    weight = models.IntegerField(help_text='Вес товара')    # Вес нужен для автоматического расчета стоймости доставки заказа
    pk_for_telegram = property(fget=lambda self: f'p||{self.pk}')

    def get_average_review_score(self):
        '''В данный момент не используется, используется в онлайн магазине для расчитывания рейтинга товара из отызвов'''
        average_score = 0.0
        if self.reviews.count() > 0:
            total_score = sum([review.rating for review in self.reviews.all()])
            average_score = total_score / self.reviews.count()
            return round(average_score, 1)

    def save(self, *args, **kwargs):
        if self.pk is not None:
            old_self = Product.objects.get(pk=self.pk)
            if old_self.photo and self.photo != old_self.photo:
                old_self.photo.delete(False)

        self.slug = slugify(self.title)
        return super(Product, self).save(*args, **kwargs)


    def get_absolute_url(self):
        return reverse('admin_panel:productdetail', kwargs={'pk': self.pk})


    def get_absolute_url_for_shop(self):
        return reverse('online_shop:product_detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title


@receiver(pre_delete, sender=Product)
def photo_delete(sender, instance, **kwargs):
    if instance.photo.name:
        instance.photo.delete(False)


class ReceptionProduct(models.Model):
    '''Модель пополнения кол-ва товара (приемка)'''
    product = models.ForeignKey(Product, on_delete=models.CASCADE, help_text='Товар')
    note = models.CharField(max_length=255, blank=True, null=True, help_text='Заметка приемки')
    price = models.DecimalField(max_digits=10, decimal_places=2, help_text='Закупочная цена')
    count = models.IntegerField(help_text='Кол-во товара в приемке')
    date = models.DateTimeField(auto_now_add=True, help_text='Дата и время приемки')
    liquidated = models.BooleanField(default=False, help_text='Ликвидация товара') # True для ликвидированного товара

    def save(self, *args, **kwargs):
        '''Обновляет кол-во товара в OfflineProduct'''
        if self.count <= 0:
            return
        if self.liquidated:
            self.product.count -= self.count
        else:
            self.product.count += self.count
        self.product.save()
        return super(ReceptionProduct, self).save(*args, **kwargs)

    def get_datetime(self):
        '''Возвращает московское время'''
        user_timezone = pytz.timezone(settings.TIME_ZONE)
        datetime = self.date.astimezone(user_timezone)
        return datetime.strftime('%m/%d/%Y %H:%M')

    def get_my_model_name(self):
        '''Возвращает имя модели, используется в детальном представлении товара, для подсвечивания строк в таблице (приемка, продажа, ликвидация)'''
        return self._meta.model_name

    def __str__(self):
        if self.liquidated:
            return f"Ликвидировано {self.count} шт. | {self.product}"
        return f"Добавленно {self.count} шт. | {self.product}"


class TelegramUser(models.Model):
    '''Модель юзеров из телеграма'''
    chat_id = models.BigIntegerField(unique=True, help_text='Id пользователя телеграм')
    first_name = models.CharField(max_length=255, blank=True, null=True, help_text='Имя')
    last_name = models.CharField(max_length=255, blank=True, null=True, help_text='Фамилия')
    username = models.CharField(max_length=255, blank=True, null=True, help_text='Юзернейм')
    fio = models.CharField(max_length=255, blank=True, null=True, help_text='ФИО для доставки')
    address = models.TextField(blank=True, null=True, help_text='Адрес доставки')
    number = models.BigIntegerField(blank=True, null=True, help_text='Телефон пользователя')
    post_index = models.IntegerField(blank=True, null=True, help_text='Почтовый индекс')
    search_data = models.CharField(max_length=255, blank=True, null=True, help_text='Данные для поиска товара')

    def __str__(self):
        if not self.username:
            return f"#{self.chat_id}|Пользователь скрыл свой юзернейм"
        return f"{self.username}"


class TelegramProductCartCounter(models.Model):
    '''Модель с counter=True используется в боте для передачи значения кол-ва в клавитуру на странице товара,
    когда пользователь нажимает - добавить в корзину, counter становится False.
    Counter=True для юзера должен быть только 1 или 0 в БД. Остальные записи где counter=False относиться к корзине юзера в телеграме
    '''
    user = models.ForeignKey(TelegramUser, on_delete=models.CASCADE, help_text='Юзер')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, help_text='Товар')
    count = models.IntegerField(default=1, help_text='Кол-во товара')
    counter = models.BooleanField(default=True, help_text='Если True, берет значение count для отображения в клавиатуре')

    

    def __str__(self):
        return f"{self.user} -- {self.count} шт."


class PayProduct(models.Model):
    '''Модель бронирования товара на оплату -  используется для оплаты через qiwi'''
    user = models.ForeignKey(TelegramUser, on_delete=models.CASCADE)
    product_pay = models.IntegerField()
    pay_comment = models.CharField(max_length=255)
    delivery_pay = models.IntegerField()
    datetime = models.DateTimeField(auto_now_add=True)


    def cancel_reservation(self):
        cart = TelegramProductCartCounter.objects.filter(Q(user=self.user) & Q(counter=False))
        for item in cart:
            item.product.count += item.count
            item.product.save()
        return self.delete()

    def save(self, *args, **kwargs):
        cart = TelegramProductCartCounter.objects.filter(Q(user=self.user) & Q(counter=False))
        for item in cart: 
            item.product.count -= item.count
            item.product.save()
        return super(PayProduct, self).save(*args, **kwargs)

    def __str__(self) -> str:
        return f"Оплата {self.product_pay+ self.delivery_pay} руб.|Коментарий для оплаты {self.pay_comment}"


class QiwiToken(models.Model):
    '''Модель для QIWI токена'''
    number = models.BigIntegerField(blank=True, null=True)
    balance = models.IntegerField(blank=True, null=True)
    token = models.CharField(max_length=255)
    active = models.BooleanField(default=False)
    blocked = models.BooleanField(default=False)


###########################################################################
class SoldProduct(models.Model):
    '''Модель проданных товаров'''
    product = models.ForeignKey(Product, on_delete=models.CASCADE, help_text='Продукт')
    price = models.DecimalField(max_digits=10, decimal_places=2, help_text='Цена на момент продажи')    
    count = models.IntegerField(help_text='Кол-во проданного товара')

app/online_shop/models.py
from django.db import models
from main_app.models import Product
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils.timezone import pytz
from django.conf import settings

class Review(models.Model):
    product = models.ForeignKey(Product, related_name='reviews', on_delete=models.CASCADE)
    author = models.CharField(max_length=50)
    rating = models.IntegerField(
    validators=[MinValueValidator(1), MaxValueValidator(5)])
    text = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ('-created',)



ORDER_STATUS = [
    ('Awaiting payment', 'Ожидает оплаты'),
    ('Created', 'Созданно'),
    ('Processing', 'В процессе'),
    ('Shipped', 'Доставляется'),
    ('Ready for pickup', 'Ожидает получения'),
    ('Completed', 'Доставленно')
    ]



class SoldSiteProduct(models.Model):
    '''Проданные товары через сайт'''
    product = models.ForeignKey(Product, on_delete=models.CASCADE, help_text='Продукт')
    price = models.DecimalField(max_digits=10, decimal_places=2, help_text='Цена на момент продажи')    
    count = models.IntegerField(help_text='Кол-во проданного товара')
    date = models.DateTimeField(auto_now_add=True, help_text='Дата и время продажи')
    order = models.ForeignKey('OrderSiteProduct', related_name='soldproduct', on_delete=models.CASCADE, help_text='Заказ')

    def get_datetime(self):
        user_timezone = pytz.timezone(settings.TIME_ZONE)
        datetime = self.date.astimezone(user_timezone)
        return datetime.strftime('%m/%d/%Y %H:%M')

    def get_my_model_name(self):
        return self._meta.model_name

    def __str__(self) -> str:
        return f"{self.product.title} - {self.count} в заказе #{self.order.pk}"


class OrderSiteProduct(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='orders', blank=True, null=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    telephone = models.CharField(max_length=20)
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    note = models.TextField(blank=True)
    transport_cost = models.DecimalField(max_digits=10, decimal_places=2)
    track_code = models.CharField(max_length=100, blank=True, null=True, help_text='Трек-код заказа')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    status = models.CharField(max_length=20, choices=ORDER_STATUS, default='Awaiting payment')
    price = models.IntegerField(blank=True, null=True)

    pay_url = models.URLField(max_length=250, blank=True, null=True, help_text='Url оплаты в QIWI')

    def set_order_price(self):
        '''Обновляет стоймость заказа при его изменении'''
        self.price = sum([x.price * x.count for x in self.soldproduct.all()])
        return self.save()

    def get_datetime(self):
        user_timezone = pytz.timezone(settings.TIME_ZONE)
        datetime = self.created.astimezone(user_timezone)
        return datetime.strftime('%m/%d/%Y %H:%M')

    def __str__(self) -> str:
        return f'Заказ #{self.id}'

app/cart/forms.py
from django import forms


class CartAddProductForm(forms.Form):
    '''Форма кол-ва товара в коризне и на странице продукта'''
    quantity = forms.IntegerField(min_value=1, widget=forms.NumberInput(attrs={'class': 'form-control text-center px-3', 'value': 1}))

app/online_shop/forms.py
from django import forms
from .models import Review
from main_app.utils import check_price_delivery
from .models import OrderSiteProduct

class ReviewForm(forms.ModelForm):
    '''Форма отзыва о товаре'''
    class Meta:
        model = Review
        fields = ['text', 'rating']
        widgets = {'text': forms.Textarea(attrs={'class': 'form-control shadow px-2', 'rows': 6}),
                   'rating': forms.RadioSelect}


class OrderCreateForm(forms.ModelForm):
    '''Форма создания заказа'''

    def clean_postal_code(self):
        data = self.cleaned_data['postal_code']
        try:
            check_postal = check_price_delivery(data, 1)
            return data
        except:
            raise forms.ValidationError("Не правильный индекс!")

    class Meta:
        model = OrderSiteProduct
        fields = ['first_name', 'last_name', 'email', 'telephone',
                  'address', 'postal_code', 'city', 'note']

        widgets = {
        'first_name': forms.TextInput(attrs={'class': 'form-control'}),
        'last_name': forms.TextInput(attrs={'class': 'form-control'}),
        'email': forms.TextInput(attrs={'class': 'form-control'}),
        'telephone': forms.TextInput(attrs={'class': 'form-control'}),
        'address': forms.TextInput(attrs={'class': 'form-control'}),
        'postal_code': forms.TextInput(attrs={'class': 'form-control'}),
        'city': forms.TextInput(attrs={'class': 'form-control'}),
        'note': forms.Textarea(attrs={'class': 'form-control', 'rows': 1})
                            }

app/online_shop/templates/product/detail.html
{% extends 'base.html' %}
{%  load my_templatetag %}
{% block title %}{{ product.name }}{% endblock %}
{% block content %}
<div class="card shadow-custom border-0 col-lg-8 mx-auto">
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <img src="{{ product.photo.url }}" alt="" class="img-fluid rounded-0">
        </div>
        <div class="col-lg-6">
            <div class="top">
                <h2 class="mt-4 font-weight-bold text-grey">
                    {{ product.name }}
                </h2>
                <!-- <div>
                    <span class="font-weight-bold text-grey">
                        Hotness:
                    </span> {{ product.shu }} SHU
                </div>
                <div>
                    <span class="font-weight-bold text-grey">
                        Volume:
                    </span> 100ml
                </div> -->
            </div>
            <div class="mt-3">
                {{ product.description | markdown_to_html | safe }}
            </div>
            {% if product.count > 0 %}
            <div class="alert alert-success my-3 text-center">
                Доступно {{product.count}} шт.
            </div>
            {% else %}
            <div class="alert alert-danger my-3 text-center">
                Нет в наличии
            </div>
            {% endif %}
            <hr>
            <div class="review">
                <span class="font-weight-bold text-grey">
                    Рейтинг: {{product.get_average_review_score}}/5.0
                </span>
                <div class="mb-3 font-weight-bold">
                    <a href="" class="text-warning" data-toggle="modal" data-target="#myModal">
                        Оставить отзыв
                    </a>
                </div>
            </div>
            <div class="mb-4">
                {% if product.count > 0 %}
                <form action="{% url 'cart:cart_add' product.pk %}" method="post">
                    {% csrf_token %}
                    <span class="input-group add-to-cart shadow-custom">
                        <div class="input-group-prepend">
                            <span class="input-group-text
            font-weight-bold px-3 btn btn-block price">
                                {{ product.price }} руб.
                            </span>
                        </div>
                        <span id="minus" class="input-group-text button_minus px-4">
                            -
                        </span>
                        <input type="number" name="quantity" class="form-control text-center px-3" value="1" max="{{product.count}}" min="1" required="" id="id_quantity">
                        <span id="plus" class="input-group-text button_plus px-4">
                            +
                        </span>
                        <div class="input-group-append">
                            <button class="btn btn-danger px-4 reduce_padding" type="submit" data-toggle="tooltip"
                                data-placement="top" title="Add to cart">
                                <i class="fas fa-shopping-cart"></i>
                            </button>
                        </div>
                    </span>
                </form>
                {% endif %}
            </div>
        </div>
    </div>
</div>
<br>



</div>




<hr class="col-7 mx-auto">
<div class="card shadow-custom border-0 col-lg-8 mx-auto mb-3">
    <h3 class="py-2 text-grey">Отзывы:</h3>
    {% for review in product.reviews.all %}
    <span class="font-weight-bold py-2 text-grey">
        {{ review.author }} - {{ review.rating }}/5 - {{ review.created }}
    </span>
    <span class="text-justify pb-2">
        {{ review.text }}
    </span>
    <hr>
    {% empty %}
    <span class="pb-2">Currently no reviews</span>
    {% endfor %}
</div>

<div class="modal" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Write your review</h5>
                <button class="close" data-dismiss="modal">&times;</button>
            </div>
            <form method="post">
                {% csrf_token %}
                <div class="modal-body">
                    <div class="bg-grey">
                        <div class="text-center pt-2">
                            Rating:
                            <div id="full-stars" class="d-inline text-center">
                                <div class="rating-group">
                                    <label class="rating__label" for="id_rating_0">
                                        <i class="rating__icon rating__icon--star fa fa-star"></i>
                                    </label>
                                    <input class="rating__input" name="rating" id="id_rating_0" value="1" type="radio"
                                        required>
                                    <label class="rating__label" for="id_rating_1">
                                        <i class="rating__icon rating__icon--star fa fa-star"></i>
                                    </label>
                                    <input class="rating__input" name="rating" id="id_rating_1" value="2" type="radio"
                                        required>
                                    <label class="rating__label" for="id_rating_2">
                                        <i class="rating__icon rating__icon--star fa fa-star"></i>
                                    </label>
                                    <input class="rating__input" name="rating" id="id_rating_2" value="3" type="radio"
                                        required>
                                    <label class="rating__label" for="id_rating_3">
                                        <i class="rating__icon rating__icon--star fa fa-star"></i>
                                    </label>
                                    <input class="rating__input" name="rating" id="id_rating_3" value="4" type="radio"
                                        required>
                                    <label class="rating__label" for="id_rating_4">
                                        <i class="rating__icon rating__icon--star fa fa-star"></i>
                                    </label>
                                    <input class="rating__input" name="rating" checked id="id_rating_4" value="5"
                                        type="radio" required>
                                </div>
                            </div>
                        </div>
                        <hr class="m-0">
                        <div class="input-field text-center p-2">
                            {{review_form.text}}
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-danger" type="submit">Confirm</button>
                </div>
            </form>
        </div>
    </div>
</div>


{% endblock content %}

app/online_shop/templates/product/order_create.html
{% extends 'base.html' %}
{% block title %}Checkout{% endblock %}
{% block content %}
<div class="card shadow-custom border-0 col-lg-7 mx-auto mb-3">
    <h3 class="py-2 font-weight-bold text-grey text-center">
        Оформление заказа:
    </h3>
    <form method="post">
        {% csrf_token %}
        {{orm.errors}}
        <div class="row">
            <div class="col-md-6">
                <div class="input-field">
                    <label class="text-muted">Имя:</label>
                    {{ form.first_name }}
                </div>
            </div>
            <div class="col-md-6">
                <div class="input-field">
                    <label class="text-muted">Фамилия:</label>
                    {{ form.last_name }}
                </div>
            </div>
            <div class="col-md-6">
                <div class="input-field">
                    <label class="text-muted">Email</label>
                    {{ form.email }}
                </div>
            </div>
            <div class="col-md-6">
                <div class="input-field">
                    <label class="text-muted">Номер телефона</label>
                    {{ form.telephone }}
                </div>
            </div>
        </div>
        <hr class="mt-0">
        <div class="row">
            <div class="col-md-6">
                <div class="input-field">
                    <label class="text-muted">Адрес</label>
                    {{ form.address }}
                </div>
            </div>
            <div class="col-md-6">
                <div class="input-field">
                    <label class="text-muted">Город</label>
                    {{ form.city }}
                </div>
            </div>
            <div class="col-md-6">
                <div id="postal_code_div" class="input-field">
                    <label class="text-muted">Почтовый индекс</label>
                    {{ form.postal_code }}
                </div>
            </div>


        </div>
        <hr>
        <h4 class="py-2 font-weight-bold text-grey">
            Стоймость доставки:
        </h4>
        

        <div class="row">
            <div class="col-md-12">
                <div class="radiobtn">

                    <h1 class='text-right' id="delivery_coast">0 руб.</h1>


                    </label>
                </div>

            </div>
        </div>
        {% if not request.user.is_authenticated %}
        <div class="mt-2 text-center">
            Уже зарегистрированы?
            <a href="{% url 'login' %}" class="text-decoration-none">
                Войти
            </a>
        </div>
        {% endif %}
        <hr class="mb-4">
        <div class="input-field">
            <label class="text-muted">Заметка к заказу</label>
            {{ form.note }}
        </div>
        <h4 class="py-2 font-weight-bold text-grey">Общая цена:
            <span id="order-total" class="text-danger float-right">{{cart_total_price}} руб.</span>
        </h4>
</div>
<div class="col-lg-7 mx-auto mb-3">
    <div class="row justify-content-end">
        <div class="col-lg-12 px-0">
            <div class="btn-group d-flex">
                <button id="sub_button" type="submit" name="manager_payment" class="btn btn-danger shadow-custom col">
                    Оплата через менеджера (Без коммиссии)
                </button>
                <button id="sub_qiwi_button" name="qiwi_payment" type="submit" class="btn btn-danger shadow-custom col">
                    Оплата QIWI (Может взиматься коммиссия 2%)
                </button>
            </div>
        </div>
        <a href="{% url 'online_shop:product_list' %}" class="btn btn-warning shadow-custom col">
            Назад
        </a>
    </div>
</div>
</form>



<script>
    var cart_coast = $('#order-total').text();
    var cart_coast_int = parseInt(cart_coast, 10);

    $('#id_postal_code').bind('input', function () {
        $.ajax({
            url: "{% url 'online_shop:validate_postal_code' %}",
            method: 'get',
            dataType: 'html',
            data: { id_postal_code: $('#id_postal_code').val() },
            success: function (data) {
                $('#postal_code_div').removeClass('error-input');
                $('#postal_code_div').addClass('success-input');
                obj = JSON.parse(data)
                $('#delivery_coast').text(obj.is_taken + ' руб.')
                $('#order-total').text((obj.is_taken + cart_coast_int) + ' руб.')
                document.getElementById("sub_button").disabled = false;
                document.getElementById("sub_qiwi_button").disabled = false;

            },
            error: function (data) {
                document.getElementById("sub_button").disabled = true;
                document.getElementById("sub_qiwi_button").disabled = true;
                $('#delivery_coast').text(0);
                $('#order-total').text(cart_coast_int + ' руб.');
                $('#postal_code_div').removeClass('success-input');
                $('#postal_code_div').addClass('error-input');
            }

        });
    });
    $(document).ready(function () {
        var postal_code = $('#id_postal_code').val()
        if (postal_code.length == 6) {
            $.ajax({
                url: "{% url 'online_shop:validate_postal_code' %}",
                method: 'get',
                dataType: 'html',
                data: { id_postal_code: $('#id_postal_code').val() },
                success: function (data) {
                    $('#postal_code_div').removeClass('error-input');
                    $('#postal_code_div').addClass('success-input');
                    obj = JSON.parse(data)
                    $('#delivery_coast').text(obj.is_taken + ' руб.')
                    $('#order-total').text((obj.is_taken + cart_coast_int) + ' руб.')
                    document.getElementById("sub_button").disabled = false;
                    document.getElementById("sub_qiwi_button").disabled = false;

                },
                error: function (data) {
                    document.getElementById("sub_button").disabled = true;
                    document.getElementById("sub_qiwi_button").disabled = true;
                    $('#delivery_coast').text(0);
                    $('#order-total').text(cart_coast_int + ' руб.');
                    $('#postal_code_div').removeClass('success-input');
                    $('#postal_code_div').addClass('error-input');
                }

            });
        }
    });

</script>

{% endblock content %}

app/online_shop/templates/product/order_created.html
{% extends 'base.html' %}
{% block title %}Заказ #{{ order.id }} создан{% endblock %}
{% block content %}
<div class="card shadow-custom border-0 col-lg-7 mx-auto mb-3">
    <div class="py-3">
        <h3 class="text-center">Спасибо за заказ. Номер вашего заказа
            <strong>{{ order.id }}</strong>
        </h3>
        
        <div class="text-center">
            На вашу почту были высланы инструкция и реквезиты для оплаты. После оплаты свяжитесь с нашим менеджером в whats app,
            viber или telegram и отправьте чек (скриншот) с оплатой и номером вашего заказа.
        </div>
    </div>
</div>
{% endblock content %}