app/cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('cart/', CartDetailView.as_view(), name='cart_detail'),            # Детальное представление корзины
    path('cart/add/<int:product_id>', cart_add, name='cart_add'),           # Добавить товар в корзину
    path('cart/remove/<int:product_id>', cart_remove, name='cart_remove'),  # Убрать товар из корзины
]

app/online_shop/urls.py
from django.urls import path
from .views import *

app_name = 'online_shop'

urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    # path('order/create', order_create, name='order_create'),
    path('order/create', CreateOrderView.as_view(), name='order_create'),
    # path('order/<int:order_id>/pdf/', invoice_pdf, name='invoice_pdf'),
    path('product/<slug:slug>', ProductDetailView.as_view(), name='product_detail'),
    path('<slug:category_slug>', ProductListView.as_view(), name='product_list_by_category'),
    path('<slug:category_slug>/<slug:subcategory_slug>', ProductListView.as_view(), name='product_list_by_subcategory'),
    path('validate/', validate_postal_code, name='validate_postal_code'),
    

]

app/vape_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from vape_shop import settings
from main_app.views import index
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls), 
    path('main/', include('main_app.urls', namespace='admin_panel')),                                                                     
    path('accounts/', include('accounts.urls'), name='index_url'),                                                   
    path('seller/', include('seller_site.urls', namespace='local_shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('online_shop.urls', namespace='online_shop')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/cart/forms.py
from django import forms


class CartAddProductForm(forms.Form):
    '''Форма кол-ва товара в коризне и на странице продукта'''
    quantity = forms.IntegerField(min_value=1, widget=forms.NumberInput(attrs={'class': 'form-control text-center px-3', 'value': 1}))

app/cart/views.py
from decimal import Decimal
from django.shortcuts import get_object_or_404, redirect, render
from django.conf import settings
from django.views import View
from main_app.models import Product
from .forms import *

class CartDetailView(View):
    '''Детальное представление корзины'''
    template_name = 'cart/cart_detail.html'
    
    def get_user_cart(self):
        '''Получение корзины юзера'''
        cart = get_cart(self.request)
        product_ids = cart.keys()
        products = Product.objects.filter(id__in=product_ids)
        temp_cart = cart.copy()
        for product in products:
            cart_item = temp_cart[str(product.pk)]
            if cart_item['quantity'] > product.count:
                cart_item['quantity'] = product.count
            cart_item['product'] = product
            cart_item['total_price'] = (Decimal(cart_item['price']) * cart_item['quantity'])
            cart_item['update_quantity_form'] = CartAddProductForm(initial={'quantity': cart_item['quantity']})
        cart_total_price = sum(Decimal(item['price']) * item['quantity'] for item in temp_cart.values())
        return (temp_cart.values(), cart_total_price)

    def get_context_data(self, **kwargs):
        context = {}
        cart = self.get_user_cart()
        context['cart'] = cart[0]
        context['cart_total_price'] = cart[1]
        return context

    def get(self, request):
        return render(request, self.template_name, context=self.get_context_data())


def get_cart(request):
    '''Получить корзину'''
    cart = request.session.get(settings.CART_ID)
    if not cart:
        cart = request.session[settings.CART_ID] = {}
    return cart


def cart_add(request, product_id):
    '''Добавление товара в корзину'''
    cart = get_cart(request)
    product = get_object_or_404(Product, pk=product_id)
    product_id = str(product.id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        if cd['quantity'] > product.count:
            '''Если юзер пытается добавить кол-во в корзину больше чем на складе'''
            cd['quantity'] = product.count
        if product_id not in cart:
            '''Если этого товара нет в корзину, создаем новый словарь в коризне'''
            cart[product_id] = {'quantity': 0, 'price': str(product.price), 'weight': product.weight}
        if request.POST.get('overwrite_qty'):
            '''Изменить кол-во товара (форма в детальной корзине)'''
            cart[product_id]['quantity'] = cd['quantity']
        else:
            '''Добавить кол-во товара в корзину'''
            if (cd['quantity'] + cart[product_id]['quantity']) > product.count:
                cart[product_id]['quantity'] = product.count
            else:
                cart[product_id]['quantity'] += cd['quantity']
        request.session.modified = True
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    '''Удаление товара из корзины'''
    cart = get_cart(request)
    product_id = str(product_id)
    if product_id in cart:
        del cart[product_id]
        request.session.modified = True
        return redirect('cart:cart_detail')


def cart_clean(request):
    '''Отчистить корзину'''
    del request.session[settings.CART_ID]

app/cart/templates/cart/cart_detail.html
{% extends 'base.html' %}
{% block title %}Shopping cart{% endblock %}
{% block content %}
<div class="card shadow-custom border-0 col-lg-10 mx-auto mb-3">
    <h3 class="py-2 font-weight-bold text-grey text-center">
        Ваш заказ:
    </h3>
    <div class="row justify-content-center py-2 text-center header-desc">
        <div class="col-lg-2 align-self-center">
            Товар
        </div>
        <div class="col-lg-2 align-self-center">
            Название
        </div>
        <div class="col-lg-2 align-self-center">
            В наличии
        </div>
        <div class="col-lg-1 align-self-center">
            Цена
        </div>
        <div class="col-lg-2 align-self-center">
            Количество
        </div>
        <div class="col-lg-3 align-self-center">
            Общая цена
        </div>
    </div>
    <hr class="mt-0">
    {% for item in cart %}
    {% with product=item.product %}
    <div class="row justify-content-center cart">
        <div class="cart-item col-4 col-lg-2">
            <a href="{% url 'online_shop:product_detail' product.slug %}">
                <img src="{{ product.photo.url }}" alt="" class="img-fluid rounded-0">
            </a>
        </div>
        <div class="cart-item product-name col-12
col-lg-2 align-self-center text-center">
            {{ product.title }}
        </div>
        <div class="cart-item col-12 col-lg-2 align-self-center">
            {% if product.count > 0 %}
            <div class="text-green mb-0 text-center">
                <i class="fas fa-check"></i>
            </div>
            {% else %}
            <div class="text-danger mb-0 text-center">
                <i class="fas fa-times"></i>
            </div>
            {% endif %}
        </div>
        <div class="cart-item col-12 col-sm-3 col-lg-1 align-self-center text-center">
            <span>{{ product.price }} руб.</span>
        </div>
        <div class="cart-item col-6 col-sm-5 col-lg-2 align-self-center">
            <form action="{% url 'cart:cart_add' product.id %}" method='post'>
                {% csrf_token %}
                <span class="input-group shopping-cart">
                    {{ item.update_quantity_form.quantity }}
                    <input type="hidden" name="overwrite_qty" value="True">
                    <div class="input-group-append">
                        <button type="submit" class="btn text-white" data-toggle="tooltip" data-placement="top"
                            title="Update">
                            <i class="fas fa-edit"></i>
                        </button>
                    </div>
                </span>
            </form>
        </div>
        <div class="cart-item col-12 col-sm-3 col-lg-2 align-self-center text-right">
            <span>{{ item.total_price }} руб.</span>
        </div>
        <div class="cart-item col-12 col-lg-1 text-right
align-self-center">
            <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn" data-toggle="tooltip" data-placement="top" title="Remove">
                    <i class="fas fa-trash-alt"></i>
                </button>
            </form>
        </div>
    </div>
    {% endwith %}
    {% empty %}
    <div class="align-self-center">
        <span class="text-center font-weight-bold text-muted lead">
            Ваша корзина пуста.
        </span>
    </div>
    {% endfor %}
    <hr>
    <div class="total-price-cart">
        <h4 class="row justify-content-center">
            <div class="col-5 col-lg-9 text-right text-grey">
                Общая цена:
            </div>
            <div class="col-5 col-lg-2 text-right text-danger">
                {{ cart_total_price|floatformat:2 }} р.
            </div>
            <div class="col-2 col-lg-1">
            </div>
        </h4>
    </div>
</div>
<hr>
<div class="col-lg-10 mx-auto mb-5">
    <div class="row justify-content-end">
        {% if cart|length > 0 %}
        <div class="col-lg-6 px-0">
            <div class="btn-group d-flex">
                <a href="{% url 'online_shop:product_list' %}" class="btn btn-warning shadow-custom col">
                    Назад
                </a>
                <a href="{% url 'online_shop:order_create' %}" class="btn btn-danger shadow-custom col">
                    Оформить заказ
                </a>
            </div>
        </div>
        {% else %}
        <div class="col-lg-3 px-0">
            <div class="btn-group d-flex">
                <a href="{% url 'online_shop:product_list' %}" class="btn btn-warning shadow-custom col">
                    Back to shop
                </a>
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock content %}