app/cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('cart/', CartDetailView.as_view(), name='cart_detail'),            # Детальное представление корзины
    path('cart/add/<int:product_id>', cart_add, name='cart_add'),           # Добавить товар в корзину
    path('cart/remove/<int:product_id>', cart_remove, name='cart_remove'),  # Убрать товар из корзины
]

app/online_shop/urls.py
from django.urls import path
from .views import *

app_name = 'online_shop'

urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    # path('order/create', order_create, name='order_create'),
    path('order/create', CreateOrderView.as_view(), name='order_create'),
    # path('order/<int:order_id>/pdf/', invoice_pdf, name='invoice_pdf'),
    path('product/<slug:slug>', ProductDetailView.as_view(), name='product_detail'),
    path('<slug:category_slug>', ProductListView.as_view(), name='product_list_by_category'),
    path('<slug:category_slug>/<slug:subcategory_slug>', ProductListView.as_view(), name='product_list_by_subcategory'),
    path('validate/', validate_postal_code, name='validate_postal_code'),
    

]

app/seller_site/urls.py
from django.urls import path, include
from .views import *

app_name = 'local_shop'

urlpatterns = [
    path('', OfflineIndexView.as_view(), name='list_product'),
    path('register_seller/', RegisterUser.as_view(), name='register_seller'),
    path('add_product/', OfflineCreateProductView.as_view(), name='create_product'),
    path('category/', OfflineCategoriesView.as_view(), name='list_category'),
    path('product/<int:pk>', OfflineProductAdminView.as_view(), name='product_detail'),
    path('make_order/', CreateOrderView.as_view(), name='create_order'),
    path('reception/', OfflineReceptionProductView.as_view(), name='create_reception'),
    path('list_order/', OfflineOrderView.as_view(), name='list_order'),
    path('stat/', OfflineStatisticView.as_view(), name='statistic'),
    path('my_sales', OfflineSellerPage.as_view(), name='my_sales'),

    path('change_order/<int:sold_pk>', change_item_order, name='change_order'),
    path('remove_item_in_order/<int:sold_pk>', remove_item_order, name='remove_item_in_order'),
    path('delete_order/<int:order_pk>', delete_order, name='delete_order')
]

app/vape_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from vape_shop import settings
from main_app.views import index
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls), 
    path('main/', include('main_app.urls', namespace='admin_panel')),                                                                     
    path('accounts/', include('accounts.urls'), name='index_url'),                                                   
    path('seller/', include('seller_site.urls', namespace='local_shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('online_shop.urls', namespace='online_shop')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/seller_site/models.py
from django.db import models
from django.db.models import Sum, Q, F
from django.urls import reverse
from django.utils.timezone import pytz
import vape_shop.settings as settings
from django.contrib.auth.models import User
from django.contrib import messages


class OfflineCategory(models.Model):
    '''Модель категорий'''
    name = models.CharField(max_length=255, help_text='Имя категории')
    price_for_seller = models.DecimalField(max_digits=10, decimal_places=2, help_text='Сумма отчисления для продавца')

    def __str__(self):
        return self.name


class OfflineSubCategory(models.Model):
    '''Модель подкатегорий'''
    category = models.ForeignKey(OfflineCategory, on_delete=models.CASCADE, help_text='Категория подкатегории')
    name = models.CharField(max_length=150, db_index=True, help_text='Имя подкатегории')

    def __str__(self):
        return self.name


class OfflineProduct(models.Model):
    '''Модель товара'''
    title = models.CharField(max_length=255, verbose_name='Название товара')
    purchase_price = models.DecimalField(max_digits=10, decimal_places=2, help_text='Закупочная цена товара')
    price = models.DecimalField(max_digits=10, decimal_places=2, help_text='Цена товара')
    count = models.IntegerField(default=0, help_text='Остаток на складе')
    subcategory = models.ForeignKey(OfflineSubCategory, on_delete=models.CASCADE, help_text='Подкатегория товара')

    def get_absolute_url(self):
        return reverse('local_shop:product_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title


class OfflineReceptionProduct(models.Model):
    '''Модель пополнения кол-ва товара (приемка)'''
    product = models.ForeignKey(OfflineProduct, on_delete=models.CASCADE, help_text='Товар')
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    note = models.CharField(max_length=255, blank=True, null=True, help_text='Заметка приемки')
    price = models.DecimalField(max_digits=10, decimal_places=2, help_text='Закупочная цена')
    count = models.IntegerField(help_text='Кол-во товара в приемке')
    date = models.DateTimeField(auto_now_add=True, help_text='Дата и время приемки')
    liquidated = models.BooleanField(default=False, help_text='Ликвидация товара') # True для ликвидированного товара

    def save(self, *args, **kwargs):
        '''Обновляет кол-во товара в OfflineProduct'''
        if self.count <= 0:
            return
        if self.liquidated:
            self.product.count -= self.count
        else:
            self.product.count += self.count
        self.product.save()
        return super(OfflineReceptionProduct, self).save(*args, **kwargs)

    def get_datetime(self):
        '''Возвращает московское время'''
        user_timezone = pytz.timezone(settings.TIME_ZONE)
        datetime = self.date.astimezone(user_timezone)
        return datetime.strftime('%m/%d/%Y %H:%M')

    def get_my_model_name(self):
        return self._meta.model_name

    def __str__(self):
        return f"{self.product} -- {self.count}"



class OfflineSoldProduct(models.Model):
    '''Модель проданных товаров'''
    user = models.ForeignKey(User, on_delete=models.PROTECT, help_text='Продавец')
    title = models.CharField(max_length=255, verbose_name='Название товара')
    product = models.ForeignKey(OfflineProduct, on_delete=models.CASCADE, help_text='Продукт')
    price = models.DecimalField(max_digits=10, decimal_places=2, help_text='Цена на момент продажи')    
    count = models.IntegerField(help_text='Кол-во проданного товара')
    date = models.DateTimeField(auto_now_add=True, help_text='Дата и время продажи')
    price_for_seller = models.IntegerField(help_text='Отчисления продавцу')
    order = models.ForeignKey('OfflineOrderingProduct', related_name='offlinesoldproduct', on_delete=models.CASCADE, help_text='Заказ')

    def save(self, *args, **kwargs):
        '''Отнимает кол-во товара в OfflineProduct'''
        if self.count <= 0:
            return
        self.product.count -= self.count
        self.product.save()
        return super(OfflineSoldProduct, self).save(*args, **kwargs)

                                                                    # вроде не используется, проверить
    def return_in_product(self, new_count):
        '''Изменяет кол-во товара при редактировании заказа'''
        if new_count <= 0:
            self.product.count += self.count
            self.product.save()
            return super(OfflineSoldProduct, self).delete()
            
        else:
            self.product.count += (self.count - new_count)
            self.product.save()
            self.count = new_count
            return super(OfflineSoldProduct, self).save()

    def delete(self, *args, **kwargs):
        self.product.count += self.count
        self.product.save()
        return super(OfflineSoldProduct, self).delete()


    def get_datetime(self):
        user_timezone = pytz.timezone(settings.TIME_ZONE)
        datetime = self.date.astimezone(user_timezone)
        return datetime.strftime('%m/%d/%Y %H:%M')
    
    def get_my_model_name(self):
        return self._meta.model_name

    def __str__(self):
        return f"{self.product} -- {self.count}"


class OfflineOrderingProduct(models.Model):
    '''Модель заказа'''
    user = models.ForeignKey(User, on_delete=models.PROTECT, help_text='Продавец')
    datetime = models.DateTimeField(auto_now_add=True, help_text='Дата и время создания заказа')
    price = models.IntegerField(blank=True, null=True)

    def set_order_price(self):
        '''Обновляет стоймость заказа при его изменении'''
        self.price = sum([x.price * x.count for x in self.offlinesoldproduct.all()])
        return self.save()

    def get_datetime(self):
        user_timezone = pytz.timezone(settings.TIME_ZONE)
        datetime = self.datetime.astimezone(user_timezone)
        return datetime.strftime('%m/%d/%Y %H:%M')

app/seller_site/forms.py
from django.db.models import fields
from .models import *
from django import forms
from django.contrib.auth.forms import  UserCreationForm


class RegisterUserForm(UserCreationForm):
      '''Форма регистрации продавца'''
      first_name = forms.CharField(label='Имя', widget=forms.TextInput(attrs={'class': 'form-control'}))
      last_name = forms.CharField(label='Фамилия', widget=forms.TextInput(attrs={'class': 'form-control'}))
      username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-control'}))
      password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
      password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-control'}))

      class Meta:
            model = User
            fields = ('username', 'password1', 'password2', 'first_name', 'last_name')

class OfflineProductForm(forms.ModelForm):
      '''Форма создания товара'''
      title = forms.CharField(label='Название', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите название товара'}))
      price = forms.IntegerField(widget=forms.TextInput(attrs={'min': '1','class': 'form-control', 'type': 'number', 'placeholder': 'Введите цену для продажи'}))
      purchase_price = forms.IntegerField(widget=forms.TextInput(attrs={'min': 1,'class': 'form-control', 'type': 'number', 'placeholder': 'Введите закупочную цену'}))
      
      class Meta:
            model = OfflineProduct
            fields = '__all__'
            fields = ['title', 'price', 'subcategory', 'purchase_price']

class OffilneCategoryForm(forms.ModelForm):
      '''Форма создания категории'''
      name = forms.CharField(widget=forms.TextInput(attrs={'style': 'float: left; width: 60%;', 'class': 'form-control', 'placeholder': 'Введите имя новой категории'}))
      price_for_seller = forms.IntegerField(widget=forms.TextInput(attrs={'min': 0,'class': 'form-control', 'type': 'number', 'placeholder': 'Сумма для продовца'}))

      class Meta:
            model = OfflineCategory
            fields = ['name', 'price_for_seller']

class OffilneChangeCategoryForm(OffilneCategoryForm):
      '''Форма изменения категории'''
      id = forms.CharField(widget=forms.HiddenInput())
      price_for_seller = forms.IntegerField(widget=forms.TextInput(attrs={'min': 0,'class': 'form-control', 'type': 'number', 'placeholder': 'Сумма для продовца', 'style': 'float: left; width: 20%;'}))
      name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите имя новой категории', 'style': 'float: right; width: 75%;'}))

      class Meta:
            model = OfflineCategory
            fields = ['id', 'name', 'price_for_seller']

class OfflineSubcategoryForm(forms.ModelForm):
      '''Форма создаения подкатегории'''
      name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите имя новой подкатегории'}))

      class Meta:
            model = OfflineSubCategory
            fields = ['name', 'category']

class OfflineChangeSubcategoryForm(OfflineSubcategoryForm):
      id = forms.CharField(widget=forms.HiddenInput())

      class Meta:
            model = OfflineSubCategory
            fields = ['id', 'name']

class OfflineReceptionForm(forms.ModelForm):
      '''Форма создания приемки'''
      count = forms.IntegerField(label='Кол-во товара:', widget=forms.TextInput(attrs={'min': 1,'class': 'form-control', 'type': 'number'}))
      note = forms.CharField(required=False, label="Заметка:", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Поле для заметки'}))

      class Meta:
            model = OfflineReceptionProduct
            fields = ['count', 'note', 'product']


class OfflineReceptionForProductViewForm(OfflineReceptionForm):
      class Meta:
            model = OfflineReceptionProduct
            fields = ['count', 'note']


class OrderChangeForm(forms.ModelForm):
      count = forms.IntegerField(label='Кол-во товара:', widget=forms.TextInput(attrs={'min': 1 , 'type': 'number', 'style': 'width: 25%'}))

      class Meta:
            model = OfflineSoldProduct
            fields = ['count']

app/seller_site/templates/seller_site/base.html
<!doctype html>
<html lang="ru">
{% load static %}
<head>
  <!-- Обязательные метатеги -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <script src="https://kit.fontawesome.com/c044e4f0d6.js" crossorigin="anonymous"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="shortcut icon" href="{% static 'icon/favicon.png' %}" type="image/png">
    <script src="https://kit.fontawesome.com/c044e4f0d6.js" crossorigin="anonymous"></script>


  <title>{{title}}</title>
</head>

<body>

  <style>
.bg-company-red {
    background-color: rgb(0, 8, 54) !important;
}
  </style>

  {% block header %}
  <header class="p-3 bg-dark text-white bg-company-red">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">

        {% if request.user.is_superuser %}
        <a style="color: white;" href="{% url 'online_shop:product_list' %}">
          <i class="fas fa-store px-3"></i></a>
        <a style="color: white;" href="{% url 'admin_panel:list_product' %}"> 
          <i class="fas fa-globe"></i>
         </a>
         {% endif %}

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          
          {% url 'local_shop:list_product' as apo %}
          {% if request.path == apo %}
          <li><a href="{% url 'local_shop:list_product' %}" class="nav-link px-2 disabled">Все товары</a></li>
          {% else %}
          <li><a href="{% url 'local_shop:list_product' %}" class="nav-link px-2 text-white">Все товары</a></li>
          {% endif %}
          
          {% url 'local_shop:register_seller' as r %}
          {% if request.user.is_superuser %}
          {% if request.path == r %}
          <li><a href="{% url 'local_shop:register_seller' %}" class="nav-link px-2 disabled">Регистрация продовца</a></li>
          {% else %}
          <li><a href="{% url 'local_shop:register_seller' %}" class="nav-link px-2 text-white">Регистрация продовца</a></li>
          {% endif %}
          {% endif %}

          {% url 'local_shop:list_order' as loo %}
          {% if request.user.is_superuser %}
          {% if request.path == loo %}
          <li><a href="{% url 'local_shop:list_order' %}" class="nav-link px-2 disabled">Заказы</a></li>
          {% else %}
          <li><a href="{% url 'local_shop:list_order' %}" class="nav-link px-2 text-white">Заказы</a></li>
          {% endif %}
          {% endif %}
          
          {% url 'local_shop:statistic' as so %}
          {% if request.user.is_superuser %}
          {% if request.path == so %}
          <li><a href="{% url 'local_shop:statistic' %}" class="nav-link px-2 disabled">Статистика</a></li>
          {% else %}
          <li><a href="{% url 'local_shop:statistic' %}" class="nav-link px-2 text-white">Статистика</a></li>
          {% endif %}
          {% endif %}

          {% url 'local_shop:my_sales' as mso %}
          {% if request.path == mso %}
          <li><a href="{% url 'local_shop:my_sales' %}" class="nav-link px-2 disabled">Мои продажи</a></li>
          {% else %}
          <li><a href="{% url 'local_shop:my_sales' %}" class="nav-link px-2 text-white">Мои продажи</a></li>
          {% endif %}
  
        </ul>


          <div class='text-center'>
            <div class="dropdown">
              <a class="btn btn-outline-light dropdown-toggle me-3" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="fas fa-plus"></i>
              </a>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                {% url 'local_shop:create_reception' as no %}
                <li><a class="dropdown-item {% if request.path == no %} disabled {% else %} {% endif %} " href="{% url 'local_shop:create_reception' %}">+ приемка</a></li>
                {% url 'local_shop:create_order' as oo %}
                <li><a href="{% url 'local_shop:create_order' %}" class="dropdown-item {% if request.path == oo %} disabled {% else %} {% endif %}">+ продажа</a></li>

                {% if request.user.is_superuser %}
                
                {% url 'local_shop:list_category' as qo %}
                
                <li><a class="dropdown-item {% if request.path == qo %} disabled {% else %} {% endif %}" href="{% url 'local_shop:list_category' %}">+ категория</a></li>
                
                {% url 'local_shop:create_product' as cp %}
                <li><a class="dropdown-item {% if request.path == cp %} disabled {% else %} {% endif %}" href="{% url 'local_shop:create_product' %}">+ товар</a></li>


                {% endif %}
              </ul>
            </div>
          </div>

          <a class="btn btn-danger " href="{% url 'logout' %}" role="button">Выход</a>
      </div>
    </div>
  </header>
  {% endblock %}


  {% block message %}
  <div class='container'>
    {% if messages %}

    {% for message in messages %}
    <div class="alert alert-{{message.tags}}" role="alert">{{ message }}</div>
    {% endfor %}

    {% endif %}
  </div>
  {% endblock %}




  <!-- <main class="flex-shrink-0"> -->

    <br>
    {% block content %}
    <!-- <div class="container">

    </div> -->
    {% endblock %}

  <!-- </main> -->

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
    
      

</body>

<!-- Модальное окно продажа начало -->

<!-- Модальное окно продажа конец  -->

<!-- Модальное окно приемка глобально начало -->

<!-- Модальное окно приемка глобально конец  -->



</html>

app/seller_site/templates/seller_site/create_reception.html
{% extends 'seller_site/base.html' %}
{% load static %}
{% block content %}
<div class="container">
<form action="{% url 'local_shop:create_reception' %}" method='POST'>
    {% csrf_token %}
    <p>
    {{ form.count.errors }}
    <label for="{{ form.count.id_for_label }}">{{form.count.label}}</label>
    {{ form.count }}</p>
    <p>
    {{ form.note.errors }}
    <label for="{{ form.note.id_for_label }}">{{form.note.label}}</label>
    {{ form.note }}</p>

    <label for="id_product" class="form-label">Товар:</label>
    <select class="form-select" name="product" id='id_product' required>
      {% for c in category %}
      <optgroup style="color:blue" label="{{c}}">
          {% for sc in c.offlinesubcategory_set.all %}
          <optgroup style="color:red" label="&nbsp;&nbsp;&nbsp;&nbsp;{{sc}}">
            {% for p in sc.offlineproduct_set.all %}
            <option style="color:black" value="{{p.pk}}">&nbsp;&nbsp;&nbsp;&nbsp;{{p.title}}</option>
          {% endfor %}
          {% endfor %}
      </optgroup>
      {% endfor %}
    </select>
    <br>
    <div class="text-center">
    <button class='btn btn-success' type="submit">Добавить</button>
</div>
</form>
</div>
{% endblock %}

app/seller_site/templates/seller_site/list_order.html
{% extends 'seller_site/base.html' %}
{% load static %}
{% block content %}

<div class='container'>
<div class='text-center'><h1>{{title}}</h1>
{% if cash_seller %}
<h4>Отчисление продавцу за день: {{ cash_seller }} руб.</h4>
{% endif %}
</div>
  <br>
  <form action="" class="" method='get'>
  
    <div class="input-group mb-3">
  <select name='user_id' style="width: 20%;" class="form-select" aria-label="Default select example">
    <option selected>Все продавцы</option>
    {% for u in users %}
    <option value="{{u.pk}}">{{u.first_name}} {{u.last_name}}</option>
    {% endfor %}
  </select>
  <button name="seller_filter" class="btn btn-outline-secondary" type="submit">Button</button>
</div>
  <br>
</form>
  <br>

<div class="accordion" id="accordionExample">
    {% for qs in queryset %}
    <div class="accordion-item">
        <h2 class="accordion-header" id="headingOne">
            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{qs.pk}}"
                aria-expanded="true" aria-controls="collapse{{qs.pk}}">
                От {{qs.get_datetime}} на сумму {{ qs.price }} руб. (Продавец - {{qs.user.first_name}} {{qs.user.last_name}})
            </button>
        </h2>
        <div id="collapse{{qs.pk}}" class="accordion-collapse collapse " aria-labelledby="heading{{qs.pk}}"
            data-bs-parent="#accordionExample">
            <div class="accordion-body">
                <div class="text-center">
                <!-- <form action="" method='post'> -->
                    <!-- {% csrf_token %} -->
                    <!-- <input type="hidden" name="order_id" value="{{qs.pk}}"> -->
                <table class="table">
                    <thead>
                      <tr>
                        <th scope="col">#</th>
                        <th scope="col">Товар</th>
                        <th scope="col">Цена за 1 шт.</th>
                        <th scope="col">Кол-во</th>
                        <th scope="col">Общая сумма</th>
                      </tr>
                    </thead>
                    <tbody>
                      {{qs.offlinesoldproduct_set.all}}
                        {% for product in qs.offlinesoldproduct.all %}
                      <tr class=''>
                        <th scope="row">{{forloop.counter}}</th>
                        <td>{{product.title}}</td>
                        <td>{{product.price}} руб.</td>
                        <td class="text-align:right;">
                          
                          <form style="display:inline;" action="{% url 'local_shop:change_order' product.pk %}" method="post">
                            {% csrf_token %}
                            <input style="width: 25%" type="number" id="id_count" name='count' pattern="" value={{product.count}} required> шт.
                            <button type="submit" class="btn" data-toggle="tooltip" data-placement="top" title="Обновить">
                            <i class="fas fa-edit"></i>
                        </button>
                          </form>

                          <form style="display:inline;"  action="{% url 'local_shop:remove_item_in_order' product.pk %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn" data-toggle="tooltip" data-placement="top" title="Удалить">
                              <i class="far fa-trash-alt"></i>
                          </button>
                          </form>
                            

                        </td>
                        <td>{% widthratio product.price 1 product.count %} руб.</td>
                      </tr>
                      {% endfor %}
                      <tr>
                        <th scope="row"></th>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>Общая сумма - {{qs.price}} руб.</td>
                      </tr>
                    </tbody>
                  </table>
            </div>
                <br>
                <div class="text-end">
                  <form action="{% url 'local_shop:delete_order' qs.pk %}">
                <button type="submit" class="btn btn-danger" name='change_order'>Удалить заказ</button>
              </form>
            </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<br>

  <nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    <li class="page-item">
      {% if page_obj.has_previous %}
      <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
        {% endif %}
      </a>
    </li>
    <li class="page-item"><a class="page-link" href="#">{{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</a></li>
    <li class="page-item">
      {% if page_obj.has_next %}
      <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
      {% endif %}
    </li>
  </ul>
</nav>
<br>

<!-- {% widthratio page_obj.number 1 -1 as res %}
{{page_obj.paginator.num_pages|add:res}}  -->
<!-- 
<nav aria-label="Page navigation example">
  <ul class="pagination">
    {% if page_obj.has_previous %}
    <li class="page-item"><a class="page-link" href="#">Previous</a></li>
    {% endif %}
    {% if page_obj.paginator.num_pages|add:res > 1 %}
    <li class="page-item"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
    <li class="page-item"><a class="page-link" href="#">{{ page_obj.number|add:"1" }}</a></li>
    <li class="page-item"><a class="page-link" href="#">{{ page_obj.number|add:"2" }}</a></li>
    {% elif page_obj.paginator.num_pages|add:res == 1 %}
    <li class="page-item"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
    <li class="page-item"><a class="page-link" href="#">{{ page_obj.number|add:"1" }}</a></li>
    {% elif page_obj.paginator.num_pages|add:res == 0 %}
    <li class="page-item"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
    {% endif %}
    {% if page_obj.has_next %}
    <li class="page-item"><a class="page-link" href="#">Next</a></li>
    {% endif %}
  </ul>
</nav> -->

</div>


{% endblock %}

app/seller_site/templates/seller_site/register.html
{% extends 'seller_site/base.html' %}

{% block content %}
<div class='container'>

<div class="text-center">
<h1>{{title}}</h1>
</div>

<form method="post">
    {% csrf_token %}
    <div class="fieldWrapper">
        {{ form.username.errors }}
        <label for="{{ form.username.id_for_label }}">Логин:</label>
        {{ form.username }}
    </div>
    <div class="fieldWrapper">
        {{ form.first_name.errors }}
        <label for="{{ form.first_name.id_for_label }}">Имя:</label>
        {{ form.first_name }}
    </div>
    <div class="fieldWrapper">
        {{ form.last_name.errors }}
        <label for="{{ form.last_name.id_for_label }}">Фамилия:</label>
        {{ form.last_name }}
    </div>
    <div class="fieldWrapper">
        {{ form.password1.errors }}
        <label for="{{ form.password1.id_for_label }}">Пароль:</label>
        {{ form.password1 }}
    </div>
    <div class="fieldWrapper">
        {{ form.password2.errors }}
        <label for="{{ form.password2.id_for_label }}">Пароль снова:</label>
        {{ form.password2 }}
    </div>
    <br>
    <div class="text-center">
    <button class='btn btn-success btn-lg' type="submit">Зарегистрировать</button>
    </div>
</form>


</div>
{% endblock %}