app/cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('cart/', CartDetailView.as_view(), name='cart_detail'),            # Детальное представление корзины
    path('cart/add/<int:product_id>', cart_add, name='cart_add'),           # Добавить товар в корзину
    path('cart/remove/<int:product_id>', cart_remove, name='cart_remove'),  # Убрать товар из корзины
]

app/main_app/urls.py
from django.urls import path
from .views import *
from .models import *
from .forms import *

app_name = 'admin_panel'

urlpatterns = [
    path('', IndexView.as_view(), name='list_product'),                                                                                     # Все товары   
    path('product/<int:pk>', ProductView.as_view(), name='productdetail'),                                                                  # Товар - подробнее
    path('category/<int:pk>', CategoryUpdateView.as_view(), name='categorydetail'),                                                         # Катеогрии - подробнее
    path('subcategory/<int:pk>', CategoryUpdateView.as_view(model=SubCategory, 
                                                            form_class=Subcategory_reqForm,
                                                            success_message = 'Подкатегория успешно обновлена!'), name='subcategorydetail'),# Подкатеогии - подробнее
    path('create_category/', CategoriesView.as_view(), name='create_category'),                                                             # Создать катеогрию
    path('create_product/', CreateProductView.as_view(), name='create_product'),                                                            # Создать товар
    path('statistic/', StatisticView.as_view(), name='statistic'),                                                                          # Общая статистика
    path('reception/', ReceptionProductView.as_view(), name='reception'),                                                                   # Приемка товара
    path('new_order/', NoPaidOrderView.as_view(), name='no_paid_order'),                                                                    # Неоплаченные заказы
    path('old_order/', PaidOrderView.as_view(), name='paid_order'),                                                                         # Оплаченные заказы
    path('qiwi_order/', QiwiOrderView.as_view(), name='qiwi_order'),                                                                        # Заказы через Qiwi


    path('site_new_order/', NoPaidSiteOrderView.as_view(), name='site_no_paid_order'),                                                                 
    path('site_old_order/', PaidSiteOrderView.as_view(), name='site_paid_order'),                                                                 
    path('site_qiwi_order/', QiwiSiteOrderView.as_view(), name='site_qiwi_order'),                                                                 

    path('qiwi/', ControlQiwiView.as_view(), name='control_qiwi'),                                                                          # Добавить, удалить токен для QIWI    

    path('change_item_bot_order/<int:sold_pk>', change_item_bot_order, name='change_item_bot_order'),                                       # Изменить кол-во товара в неоплаченном заказе (бот)
    path('change_item_site_order/<int:sold_pk>', change_item_site_order, name='change_item_site_order'),                                    # Изменить кол-во товара в неоплаченном заказе (сайт)
    path('delete_bot_order/<int:order_pk>', delete_bot_order, name='delete_bot_order'),                                                     # Удалить заказ (бот)  
    path('delete_site_order/<int:order_pk>', delete_site_order, name='delete_site_order'),                                                  # Удалить заказ (сайт)
    path('remove_item_bot_order/<int:sold_pk>', remove_item_bot_order, name='remove_item_bot_order'),                                       # Удалить товар из заказа (бот)
    path('remove_item_site_order/<int:sold_pk>', remove_item_site_order, name='remove_item_site_order'),                                    # Удалить товар из заказа (сайт)
    path('add_track_code_in_bot_order/<int:order_pk>', add_track_code_in_order, name='add_track_code_in_order'),                                # Добавить трек код
    path('add_track_code_in_site_order/<int:order_pk>', add_track_code_and_status_order_site, name='add_track_code_in_site_order'),                                # Добавить трек код
    ]

app/online_shop/urls.py
from django.urls import path
from .views import *

app_name = 'online_shop'

urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    # path('order/create', order_create, name='order_create'),
    path('order/create', CreateOrderView.as_view(), name='order_create'),
    # path('order/<int:order_id>/pdf/', invoice_pdf, name='invoice_pdf'),
    path('product/<slug:slug>', ProductDetailView.as_view(), name='product_detail'),
    path('<slug:category_slug>', ProductListView.as_view(), name='product_list_by_category'),
    path('<slug:category_slug>/<slug:subcategory_slug>', ProductListView.as_view(), name='product_list_by_subcategory'),
    path('validate/', validate_postal_code, name='validate_postal_code'),
    

]

app/vape_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from vape_shop import settings
from main_app.views import index
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls), 
    path('main/', include('main_app.urls', namespace='admin_panel')),                                                                     
    path('accounts/', include('accounts.urls'), name='index_url'),                                                   
    path('seller/', include('seller_site.urls', namespace='local_shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('online_shop.urls', namespace='online_shop')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/main_app/models.py
from django.db import models
from django.db.models.query_utils import Q
from django.urls import reverse
from django.utils.timezone import pytz
from django.conf import settings
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver
from pytils.translit import slugify


class Category(models.Model):
    '''Модель категорий'''
    name = models.CharField(max_length=255, help_text='Имя категории')
    photo = models.ImageField(upload_to='category_img/', help_text='Фото категории')
    slug = models.SlugField(max_length=100, unique=True)
    pk_for_telegram = property(fget=lambda self: f'c||{self.pk}')    # Нужен для идентификации в телеграм боте
    max_count_product = models.IntegerField()

    def save(self, *args, **kwargs):
        if self.pk is not None:
            old_self = Category.objects.get(pk=self.pk)
            if old_self.photo and self.photo != old_self.photo:
                old_self.photo.delete(False)

        self.slug = slugify(self.name)
        return super(Category, self).save(*args, **kwargs)

    def get_absolute_url_for_shop(self):
        return reverse('online_shop:product_list_by_category', kwargs={'category_slug': self.slug})
        
    def __str__(self):
        return self.name

@receiver(pre_delete, sender=Category)
def photo_delete(sender, instance, **kwargs):
    if instance.photo.name:
        instance.photo.delete(False)


class SubCategory(models.Model):
    '''Модель подкатегорий'''
    category = models.ForeignKey(Category, on_delete=models.CASCADE, help_text='Категория подкатегории')
    name = models.CharField(max_length=150, db_index=True, help_text='Имя подкатегории')
    photo = models.ImageField(upload_to='subcategory_img/', help_text='Фотоподкатегории')
    slug = models.SlugField(max_length=100, unique=True)
    pk_for_telegram = property(fget=lambda self: f'sc||{self.pk}')

    def save(self, *args, **kwargs):
        if self.pk is not None:
            old_self = SubCategory.objects.get(pk=self.pk)
            if old_self.photo and self.photo != old_self.photo:
                old_self.photo.delete(False)

        self.slug = slugify(self.name)
        return super(SubCategory, self).save(*args, **kwargs)


    def get_absolute_url_for_shop(self):
        return reverse('online_shop:product_list_by_subcategory', kwargs={'category_slug': self.category.slug, 'subcategory_slug': self.slug})

    def __str__(self):
        return self.name


@receiver(pre_delete, sender=SubCategory)
def photo_delete(sender, instance, **kwargs):
    if instance.photo.name:
        instance.photo.delete(False)


class Product(models.Model):
    '''Модель товара'''
    title = models.CharField(max_length=255, verbose_name='Название товара')
    photo = models.ImageField(upload_to='product_img/', help_text='Фото товара')
    description = models.TextField(help_text='Описание товара')
    price = models.DecimalField(max_digits=10, decimal_places=2, help_text='Цена товара')
    count = models.IntegerField(default=0, help_text='Остаток на складе')
    slug = models.SlugField(max_length=100, unique=True)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE, help_text='Подкатегория товара')
    weight = models.IntegerField(help_text='Вес товара')    # Вес нужен для автоматического расчета стоймости доставки заказа
    pk_for_telegram = property(fget=lambda self: f'p||{self.pk}')

    def get_average_review_score(self):
        '''В данный момент не используется, используется в онлайн магазине для расчитывания рейтинга товара из отызвов'''
        average_score = 0.0
        if self.reviews.count() > 0:
            total_score = sum([review.rating for review in self.reviews.all()])
            average_score = total_score / self.reviews.count()
            return round(average_score, 1)

    def save(self, *args, **kwargs):
        if self.pk is not None:
            old_self = Product.objects.get(pk=self.pk)
            if old_self.photo and self.photo != old_self.photo:
                old_self.photo.delete(False)

        self.slug = slugify(self.title)
        return super(Product, self).save(*args, **kwargs)


    def get_absolute_url(self):
        return reverse('admin_panel:productdetail', kwargs={'pk': self.pk})


    def get_absolute_url_for_shop(self):
        return reverse('online_shop:product_detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title


@receiver(pre_delete, sender=Product)
def photo_delete(sender, instance, **kwargs):
    if instance.photo.name:
        instance.photo.delete(False)


class ReceptionProduct(models.Model):
    '''Модель пополнения кол-ва товара (приемка)'''
    product = models.ForeignKey(Product, on_delete=models.CASCADE, help_text='Товар')
    note = models.CharField(max_length=255, blank=True, null=True, help_text='Заметка приемки')
    price = models.DecimalField(max_digits=10, decimal_places=2, help_text='Закупочная цена')
    count = models.IntegerField(help_text='Кол-во товара в приемке')
    date = models.DateTimeField(auto_now_add=True, help_text='Дата и время приемки')
    liquidated = models.BooleanField(default=False, help_text='Ликвидация товара') # True для ликвидированного товара

    def save(self, *args, **kwargs):
        '''Обновляет кол-во товара в OfflineProduct'''
        if self.count <= 0:
            return
        if self.liquidated:
            self.product.count -= self.count
        else:
            self.product.count += self.count
        self.product.save()
        return super(ReceptionProduct, self).save(*args, **kwargs)

    def get_datetime(self):
        '''Возвращает московское время'''
        user_timezone = pytz.timezone(settings.TIME_ZONE)
        datetime = self.date.astimezone(user_timezone)
        return datetime.strftime('%m/%d/%Y %H:%M')

    def get_my_model_name(self):
        '''Возвращает имя модели, используется в детальном представлении товара, для подсвечивания строк в таблице (приемка, продажа, ликвидация)'''
        return self._meta.model_name

    def __str__(self):
        if self.liquidated:
            return f"Ликвидировано {self.count} шт. | {self.product}"
        return f"Добавленно {self.count} шт. | {self.product}"


class TelegramUser(models.Model):
    '''Модель юзеров из телеграма'''
    chat_id = models.BigIntegerField(unique=True, help_text='Id пользователя телеграм')
    first_name = models.CharField(max_length=255, blank=True, null=True, help_text='Имя')
    last_name = models.CharField(max_length=255, blank=True, null=True, help_text='Фамилия')
    username = models.CharField(max_length=255, blank=True, null=True, help_text='Юзернейм')
    fio = models.CharField(max_length=255, blank=True, null=True, help_text='ФИО для доставки')
    address = models.TextField(blank=True, null=True, help_text='Адрес доставки')
    number = models.BigIntegerField(blank=True, null=True, help_text='Телефон пользователя')
    post_index = models.IntegerField(blank=True, null=True, help_text='Почтовый индекс')
    search_data = models.CharField(max_length=255, blank=True, null=True, help_text='Данные для поиска товара')

    def __str__(self):
        if not self.username:
            return f"#{self.chat_id}|Пользователь скрыл свой юзернейм"
        return f"{self.username}"


class TelegramProductCartCounter(models.Model):
    '''Модель с counter=True используется в боте для передачи значения кол-ва в клавитуру на странице товара,
    когда пользователь нажимает - добавить в корзину, counter становится False.
    Counter=True для юзера должен быть только 1 или 0 в БД. Остальные записи где counter=False относиться к корзине юзера в телеграме
    '''
    user = models.ForeignKey(TelegramUser, on_delete=models.CASCADE, help_text='Юзер')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, help_text='Товар')
    count = models.IntegerField(default=1, help_text='Кол-во товара')
    counter = models.BooleanField(default=True, help_text='Если True, берет значение count для отображения в клавиатуре')

    

    def __str__(self):
        return f"{self.user} -- {self.count} шт."


class PayProduct(models.Model):
    '''Модель бронирования товара на оплату -  используется для оплаты через qiwi'''
    user = models.ForeignKey(TelegramUser, on_delete=models.CASCADE)
    product_pay = models.IntegerField()
    pay_comment = models.CharField(max_length=255)
    delivery_pay = models.IntegerField()
    datetime = models.DateTimeField(auto_now_add=True)


    def cancel_reservation(self):
        cart = TelegramProductCartCounter.objects.filter(Q(user=self.user) & Q(counter=False))
        for item in cart:
            item.product.count += item.count
            item.product.save()
        return self.delete()

    def save(self, *args, **kwargs):
        cart = TelegramProductCartCounter.objects.filter(Q(user=self.user) & Q(counter=False))
        for item in cart: 
            item.product.count -= item.count
            item.product.save()
        return super(PayProduct, self).save(*args, **kwargs)

    def __str__(self) -> str:
        return f"Оплата {self.product_pay+ self.delivery_pay} руб.|Коментарий для оплаты {self.pay_comment}"


class QiwiToken(models.Model):
    '''Модель для QIWI токена'''
    number = models.BigIntegerField(blank=True, null=True)
    balance = models.IntegerField(blank=True, null=True)
    token = models.CharField(max_length=255)
    active = models.BooleanField(default=False)
    blocked = models.BooleanField(default=False)


###########################################################################
class SoldProduct(models.Model):
    '''Модель проданных товаров'''
    product = models.ForeignKey(Product, on_delete=models.CASCADE, help_text='Продукт')
    price = models.DecimalField(max_digits=10, decimal_places=2, help_text='Цена на момент продажи')    
    count = models.IntegerField(help_text='Кол-во проданного товара')

app/main_app/templates/main_app/base.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
  <!-- Обязательные метатеги -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="shortcut icon" href="{% static 'icon/favicon.png' %}" type="image/png">
    <script src="https://kit.fontawesome.com/c044e4f0d6.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>

  <title>{% block title %} {% endblock %}</title>
</head> 

<body>

  {% block header %}
  <header class="p-3 bg-dark text-white">
    <div class="container-xxl">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a style="color: white;" href="{% url 'online_shop:product_list' %}">
          <i class="fas fa-store px-3"></i></a>
       
        <a style="color: white;" href="{% url 'local_shop:list_product' %}"> 
          <i class="far fa-building"></i>
         </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">

          {% url 'admin_panel:list_product' as ap %}
          {% if request.path == ap %}
          <li><a href="{% url 'admin_panel:list_product' %}" class="nav-link px-2 disabled">Список товаров</a></li>
          {% else %}
          <li><a href="{% url 'admin_panel:list_product' %}" class="nav-link px-2 text-white">Список товаров</a></li>
          {% endif %}

          {% url 'admin_panel:statistic' as us %}
          {% if request.path == us %}
          <li><a href="{% url 'admin_panel:statistic' %}" class="nav-link px-2 disabled">Общая статистика</a></li>
          {% else %}
          <li><a href="{% url 'admin_panel:statistic' %}" class="nav-link px-2 text-white">Общая статистика</a></li>
          {% endif %}

          {% url 'admin_panel:reception' as r %}
          {% if request.path == r %}
          <li><a href="{% url 'admin_panel:reception' %}" class="nav-link px-2 disabled">Прием товаров</a></li>
          {% else %}
          <li><a href="{% url 'admin_panel:reception' %}" class="nav-link px-2 text-white">Прием товаров</a></li>
          {% endif %}

          {% url 'admin_panel:control_qiwi' as q %}
          {% if request.path == q %}
          <li><a href="{% url 'admin_panel:control_qiwi' %}" class="nav-link px-2 disabled">Управление киви</a></li>
          {% else %}
          <li><a href="{% url 'admin_panel:control_qiwi' %}" class="nav-link px-2 text-white">Управление киви</a></li>
          {% endif %}

          <div class="dropdown">
            <a class="btn btn-outline-light dropdown-toggle px-2" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
              Заказы (Бот)
            </a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              {% url 'admin_panel:no_paid_order' as no %}
              {% if request.path == no %}
              <li><a class="dropdown-item disabled" href="{% url 'admin_panel:no_paid_order' %}">Неоплаченные заказы</a></li>
              {% else %}
              <li><a class="dropdown-item" href="{% url 'admin_panel:no_paid_order' %}">Неоплаченные заказы</a></li>
              {% endif %}

              {% url 'admin_panel:paid_order' as oo %}
              {% if request.path == oo %}
              <li><a href="{% url 'admin_panel:paid_order' %}" class="dropdown-item disabled">Оплаченные заказы</a></li>
              {% else %}
              <li><a href="{% url 'admin_panel:paid_order' %}" class="dropdown-item">Оплаченные заказы</a></li>
              {% endif %}

              {% url 'admin_panel:qiwi_order' as qo %}
              {% if request.path == qo %}
              <li><a class="dropdown-item disabled" href="{% url 'admin_panel:qiwi_order' %}">Qiwi заказы</a></li>
              {% else %}
              <li><a class="dropdown-item" href="{% url 'admin_panel:qiwi_order' %}">Qiwi заказы</a></li>
              {% endif %}
            </ul>
          </div>

          <div class="dropdown px-2">
            <a class="btn btn-outline-light dropdown-toggle px-2" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
              Заказы (Сайт)
            </a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              {% url 'admin_panel:site_no_paid_order' as qo %}
              {% if request.path == qo %}
              <li><a class="dropdown-item disabled" href="{% url 'admin_panel:site_no_paid_order' %}">Неоплаченные заказы через сайт</a></li>
              {% else %}
              <li><a class="dropdown-item" href="{% url 'admin_panel:site_no_paid_order' %}">Неоплаченные заказы через сайт</a></li>
              {% endif %}

              {% url 'admin_panel:site_paid_order' as qo %}
              {% if request.path == qo %}
              <li><a class="dropdown-item disabled" href="{% url 'admin_panel:site_paid_order' %}">Оплаченные заказы через сайт</a></li>
              {% else %}
              <li><a class="dropdown-item" href="{% url 'admin_panel:site_paid_order' %}">Оплаченные заказы через сайт</a></li>
              {% endif %}

              {% url 'admin_panel:site_qiwi_order' as qo %}
              {% if request.path == qo %}
              <li><a class="dropdown-item disabled" href="{% url 'admin_panel:site_qiwi_order' %}">Оплаченные заказы через сайт (QIWI)</a></li>
              {% else %}
              <li><a class="dropdown-item" href="{% url 'admin_panel:site_qiwi_order' %}">Оплаченные заказы через сайт (QIWI)</a></li>
              {% endif %}
            </ul>
          </div>

        </ul> 

        

        <div class="text-end">
          <div class="btn-group">
            <a class="btn btn-outline-light me-2" href="{% url 'admin_panel:create_category' %}" role="button">+ Категория</a>
          </div><!-- /btn-group -->
          <div class="btn-group">
            <a class="btn btn-outline-light me-2" href="{% url 'admin_panel:create_product' %}" role="button">+ Товар</a>
          </div><!-- /btn-group -->
          <a class="btn btn-danger " href="{% url 'logout' %}" role="button">Выход</a>
        </div>
      </div>
    </div>
  </header>
  {% endblock %}


  {% block message %}
  <div class='container'>
    {% if messages %}

    {% for message in messages %}
    <div class="alert alert-success" role="alert">{{ message }}</div>
    {% endfor %}

    {% endif %}
  </div>
  {% endblock %}




  <main class="flex-shrink-0">

    <br>
    {% block content %}

    {% endblock %}

  </main>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
</body>

</html>

app/main_app/templates/main_app/create_product.html
{% extends 'main_app/base.html' %}
{% load static %}

{% block title %} Создать товар {% endblock %}

{% block content %}

<div class='container'>

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row align-items-center">
        <div class="col">
            <div class="fieldWrapper">
                {{ form.title.errors }}
                <label for="{{ form.title.id_for_label }}">Название товара:</label>
                {{ form.title }}
            </div>
            <br>
            <div class="fieldWrapper">
                {{ form.description.errors }}
                <label for="{{ form.description.id_for_label }}">Описание:</label> <div class="text-end text-muted" id='textarea_count'>0/1000</div>
                {{ form.description }}
            </div>
            <br>
        </div>

    {{ form.non_field_errors }}


    <div class="row">
        <div class="col-sm">
            <div class="fieldWrapper">
                {{ form.price.errors }}
                <label for="{{ form.price.id_for_label }}">Цена:</label>
                {{ form.price }}
            </div>
        </div>
        <div class="col-sm">
            <div class="fieldWrapper">
                {{ form.weight.errors }}
                <label for="{{ form.weight.id_for_label }}">Вес:</label>
                {{ form.weight }}
            </div>
        </div>
        <div class="col-sm">
            <div class="fieldWrapper">
                {{ form.subcategory.errors }}
                <label for="{{ form.subcategory.id_for_label }}">Категория:</label>
                <!-- {{ product_form.subcategory }} -->

                <select class="form-select" name="subcategory" required id='id_subcategory'>
                    {% for c in category %}
                    <optgroup label="{{c}}">
                        {% for sc in c.subcategory_set.all %}
                        {% if sc == product.subcategory %}
                        <option selected value="{{sc.pk}}">{{sc.name}}</option>
                        {% else %}
                        <option value="{{sc.pk}}">{{sc.name}}</option>
                        {% endif %}
                        {% endfor %}
                    </optgroup>
                    {% endfor %}
                </select>
            </div>
        </div>
    </div>
    <br>

    <div class="fieldWrapper">
        {{ form.photo.errors }}
        <label for="{{ form.photo.id_for_label }}">Фото:</label>
        {{ form.photo }}
    </div>
 
    <div class='text-end'>
        <br>
        <input type="submit" class='btn btn-success btn-lg' name='update' value="Создать">
        {% url 'admin_panel:create_product' as ap %}
        {% if request.path == ap %}
        {% else %}
        <input type="submit" class='btn btn-danger btn-lg' name='delete' value="Удалить">
        {% endif %}
    </div>
</form>
</div>

<script>
    $('#id_description').bind('input', function () {
        var len = $("#id_description").val().length;
        $('#textarea_count').text(len + '/1000')
        if (len > 1000) {
            $('#id_description').removeClass('alert-success');
            $('#id_description').addClass('alert-danger');
        } else {
            $('#id_description').removeClass('alert-danger');
            $('#id_description').addClass('alert-success');
        }

    });
</script>
{% endblock %}

app/main_app/templates/main_app/list_category.html
{% extends 'main_app/base.html' %}
{% load static %}

{% block title %} Категории {% endblock %}

{% block content %}

<div class='container'>

<div class="text-center">
    <h1>Категории</h1>
</div>
<br>
<form action="{% url 'admin_panel:create_category' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="input-group mb-3">
        {{ category_form.max_count_product }}   
        <span class="input-group-text">@</span>
        {{ category_form.name }}
      </div>

    <br>

    <div class="row">

        <div class="col-8">
            {{ category_form.photo }}
        </div>
        <div class="col">
            <div class="text-end">
                <button class="btn btn-success" type="Submit" id="button-addon2" name="create_category">Создать</button>
            </div>
        </div>
    </div>
</form>
<br>
</div>

<div class="accordion" id="accordionExample">
    {% for c in queryset %}
    <div class="accordion-item">
        <h2 class="accordion-header" id="headingOne">
            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-{{c.pk}}"
                aria-expanded="true" aria-controls="collapse-{{c.pk}}">
                {{c}}
            </button>
        </h2>
        <div id="collapse-{{c.pk}}" class="accordion-collapse collapse" aria-labelledby="headingOne"
            data-bs-parent="#accordionExample">
            <div class="accordion-body">


                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Имя подкатегории</th>
                            <th scope="col"></th>

                        </tr>
                    </thead>
                    <tbody>
                        {% for sc in c.subcategory_set.all %}
                        <tr>
                            <th scope="row">{{sc.pk}}</th>
                            <td>{{sc.name}}</td>
                            <td>
                                <div class="text-end">
                                    <a class="btn btn-primary btn-sm" href="{% url 'admin_panel:subcategorydetail' pk=sc.pk %}"
                                        role="button">Изменить</a>
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>

                <div class="container">
                    <div class="row">
                        <div class="col">
                            <div class="mb-3">
                                <!-- Поле ввода файла -->
                                <div class='text-end'>
                                    <!-- <input class="form-control-sm" type="file" id="formFile"> -->
                                    <form action="" method='post' enctype="multipart/form-data">
                                        {% csrf_token %}
                                        {{sc_form.name}}
                                        
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col">
                            <!-- <div class="input-group mb-3"> -->
                            <input type="hidden" id="id_category" name="category" value="{{c.pk}}">
                            
                            {{sc_form.photo}}


                        </div>
                    </div>
                <br>
                <div class='row'>
                    <div class="col">
                        <a class="btn btn-warning btn-sm" href="{% url 'admin_panel:categorydetail' pk=c.pk %}"
                            role="button">Изменить</a>
                    </div>

                    <div class='col'>
                        <div class='text-end'>
                            <button class="btn btn-outline-success" type="submit" name="create_sc">Создать</button>
                        </div>
                    </div>
                </div>
                </form>

            </div>
        </div>
    </div>
</div>
</div>

    {% endfor %}
</div>




{% endblock %}